### ISSUE TITLE
Should i put my material in here? 

### ISSUE THREAD

**Issue by sckott** [jhollist/iale_open_science#1]
that is, send a PR? or somewhere else?

**Comment by jhollist** [comment]
@sckott here is fine.

Workflow I've been using:
1. Edits to .Rmd in rmd_posts/
2. `make` (make file passes through knitr and moves output .md into _posts/)
3. `make git` (bad practice I am sure, but made it easy when it was just me, pushes everything up)

If your .Rmd is set up similar to the other ones (the Git one is somewhat far along as an example), you can just push directly (I think I added you).

**Comment by sckott** [comment]
k, will do
