### ISSUE TITLE
some pkgs not on CRAN

### ISSUE THREAD

**Issue by sckott** [jhollist/iale_open_science#7]
One package for my lesson tomorrow may not have binaries up by time of workshop start, and one definitely won't.  Should I put instructions in the lesson for getting from github, or just do that before we start separately?

**Comment by jhollist** [comment]
Instructions in the lesson would be nice, but not necessary.  We can walk folks through that during, especially since we have as many instructors as we do participants!

**Comment by sckott** [comment]
Okay, i'll add install instructions
